name: Deploy Readme to WordPress.org SVN

on:
  push:
    branches: [ "master" ] # or main
    paths:
      - 'readme.txt'

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Readme to SVN
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          GENERATE_ZIP: false
