name: Update Readme on WordPress.org

on:
  push:
    branches: [ "master" ] # or main
    paths:
      - 'readme.txt'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SVN
        run: sudo apt-get install -y subversion

      - name: Commit readme.txt to WordPress.org SVN
        run: |
          # Checkout trunk only
          svn checkout --depth empty https://plugins.svn.wordpress.org/bangla-date-display/tags/10.1.0 svn-tag
          cd svn-tag
          svn update readme.txt
          
          # Copy updated readme.txt from repository
          cp ../readme.txt readme.txt
          
          # Commit changes to SVN
          svn commit -m "Update Tested up to / readme.txt via GitHub Actions" \
            --username "${{ secrets.SVN_USERNAME }}" \
            --password "${{ secrets.SVN_PASSWORD }}" \
            --non-interactive
